# Python basics

In [ ]:
rishi = 100 #declaring a variable

In [ ]:
print(rishi) #printing a var

100


In [ ]:
# Numerical Datatypes
# Integers
# numbers without decimals i.e 1,2,3,4,5,-1,-2,-3,-4,-5
# Floats
# numbers with decimals i.e 1.0,2.0,3.0,4.0,5.0,-1.0,-2.0,-3.0,-4.0,-5.0
# Complex

In [ ]:
int_var = 123414
float_var = 314.2345

In [ ]:
# String
'jfgja3478539#$%#@'
"sdjfb2734856#$%#%"

'sdjfb2734856#$%#%'

In [ ]:
str_var = "rishi"
email = "rishi@123"
marks = "100"

In [ ]:
print(str_var)

rishi


In [ ]:
print(str_var[0])
print(str_var[1])
print(str_var[2])
print(str_var[3])
print(str_var[4])

r
i
s
h
i


In [ ]:
print(str_var[-1])
print(str_var[-2])
print(str_var[-3])
print(str_var[-4])
print(str_var[-5])

i
h
s
i
r


In [ ]:
# Boolean
# True
# False

In [ ]:
# List
# Tuple
# Set
# Dictionary

In [ ]:
# Both list and tuple are ordered collections
# any data can be stored
# no max cap on size
# comma separated values

list=[]
tuple=()

In [ ]:
list=[1,2,3,4,5]
tuple=(1,2,3,4,5)

In [ ]:
# Mutability
# List is mutable
# Tuple is immutable
my_list = ['python','java','c++']
my_tuple = ('python','java','c++')

In [ ]:
print(my_list[0])

python


In [ ]:
my_list[0] = 'rishi'
print(my_list)

['rishi', 'java', 'c++']


In [ ]:
# my_tuple = ('rishi','java','c++')

In [ ]:
# Dictionary
# Key value pair
my_dict={1:'rishi','age':13,}

In [ ]:
print(my_dict)

{1: 'rishi', 'age': 13}


In [ ]:
print(my_dict['age'])

13


In [ ]:
# Type Conversion
# Implicit - automatically done by python
a = 10 #int->float 10.0
b = 15.5 #float
c = a+b
print(c)

25.5


In [ ]:
# a
# a=int(a)
# d=float(a)
# str(a)

10

In [ ]:
# Explicit
x = 10
y = '20'
y = int(y)
z = x+y
print(z)

30


In [ ]:
# Operators
# Arithmetic Operators
# Assignment Operators
# Comparison Operators
# Logical Operators
# Identity Operators
# Membership Operators
# Bitwise Operators

In [ ]:
# Arithmetic operators
# + Addition and concatenation
res = 35+25
print(res)
res = '35'+'25'
print(res)
# -
# *
# / division
print(15/4)
# % modulo
print(15%4)
# ** exponentiation
print(23**3) #23*23*23
# // floor division
print(15//4)

60
3525
3.75
3
12167
3


In [ ]:
# comparison operators
# == equal to
print(10==10)
# != not equal to
# > greater than
# < less than
# >= greater than or equal to
# <= less than or equal to

In [ ]:
# Assignment operators
# =
# Augumented assignment operators or compound operators
# +=
a = 5
a += 10 # a = a+10
print(a)
# -=
# *=
# /=
# %=
# **=
# //=

15


In [ ]:
# Logical Operators or Boolean operators
# and
print(True and True)
print(True and False)
print(False and True)
print(False and False)
# or
print(True or True)
print(True or False)
print(False or True)
print(False or False)
# not
print(not True)
print(not False)

True
False
False
False
True
True
True
False


In [ ]:
# Identity operators
# is ==
# is not !=

In [ ]:
# membership operators
# in
# not in
# x in y
# x -> int, str, float
# y -> list, tuple, set, dictionary

In [ ]:
# bitwise operators
# & and
# | or
# ^ xor
# ~ not
# << left shift
# >> right shift

In [ ]:
# Namespace
# Built-in
# print,if,else,input,int,float
# Global
# Local

In [ ]:
# Regulate Control flow
# if else elif - conditional statements
# for - loop
# while - loop
# functions

## Topics Covered



* Functions
* Function with optional args
* Functions with return value
* assigning function to a variable
* Types and Sequences
* String access, slicing, concat

* Dictionary
 * declaration
 * iteration using key
 * using value
 * both key and value
* Unpacking data


## Data and Times

In [1]:
import datetime as dt
import time as tm

In [3]:
tm.time() #time in seconds since 1st jan 1970

1722961142.031816

In [6]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [7]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2024, 8, 6, 16, 19, 56)

## Class and Object

In [ ]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

## Map

map(function,iterable) return a map object that can be iterated

## Lambda and List Comprehensions

In [12]:
x = lambda a,b,c : a+b

In [13]:
x(1,2,3)

3

In [14]:
[n for n in range(10) if n%2==0]

[0, 2, 4, 6, 8]

# Numpy

In [3]:
import numpy as np
import pandas as pd

### Declaring and accessing

In [ ]:
data = 123
arr_0d = np.array(data)
print(arr_0d) #0 dimentional numpy array

123


In [ ]:
data = [1,2,3,4,5] #python list
arr_1d = np.array(my_list)
print(arr_1d) #1 dimentional numpy array

[1 2 3 4 5]


In [15]:
print(arr_1d[3])

NameError: name 'arr_1d' is not defined

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d) #2 dimentional numpy array

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr_2d[0])

[1 2 3]


In [ ]:
print(arr_2d[0][0]) #method 1

1


In [ ]:
print(arr_2d[0,1]) #method 2

2


In [ ]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d) #3 dimentional numpy array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
my_list = ['python','java','c']

In [ ]:
print(my_list[1])

java


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr[0,0,0] = 29386 #mutation

In [ ]:
print(arr)

[[[29386     2     3]
  [    4     5     6]]

 [[    7     8     9]
  [   10    11    12]]]


In [ ]:
arr1 = np.array([1,2,3,4],ndmin=1)
arr2 = np.array([[1,2],[3,4]],ndmin=2)
print(arr1.shape) #shape of array
print(arr2.shape)
print(arr1.size) #no of elements
print(arr2.size)

(4,)
(2, 2)
4
4


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
az1d = np.zeros(15)
print(az1d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
az2d = np.zeros([3,4])
print(az2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
np.random.rand(3,2)

array([[0.17741344, 0.97900231],
       [0.60839068, 0.50880073],
       [0.70895657, 0.02708382]])

In [22]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Array Operations

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [ ]:
print(np.add(a,b))

[[ 6  7]
 [10 11]]


In [ ]:
print(np.subtract(b,a))

[[4 4]
 [4 4]]


In [ ]:
print(np.multiply(a,b))

[ 5 12 21 32]


In [ ]:
print(np.divide(a,b))

[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(np.floor_divide(a,b))

[[0 0]
 [0 0]]


In [ ]:
print(np.mod(a,b))

[[1 2]
 [3 4]]


In [ ]:
x = np.array([[5,6],[7,8],[9,10]])
y = np.array([[1,2,3]])

In [ ]:
print(x.shape)
print(y.shape)

(3, 2)
(1, 3)


In [ ]:
print(np.add(x,y))

ValueError: operands could not be broadcast together with shapes (3,2) (1,3) 

In [ ]:
c = np.array([10, 20, 30, 40])
d = np.array([15, 25, 20, 50])


In [ ]:
greater_than = np.greater(c, d)
print("Greater than:", greater_than)


Greater than: [False False  True False]


In [ ]:
lesser_than = np.less(c, d)
print("Lesser than:", lesser_than)


Lesser than: [ True  True False  True]


In [ ]:
equals = np.equal(c,d)
print('Equals:',equals)

Equals: [False False False False]


In [ ]:
not_equal = np.not_equal(c,d)
print('Not Equal',not_equal)

Not Equal [ True  True  True  True]


In [ ]:
np.less_equal(c,d)

array([ True,  True, False,  True])

In [ ]:
np.greater_equal(c,d)

array([False, False,  True, False])

In [ ]:
np.logical_and(c>1,d>2)

array([ True,  True,  True,  True])

In [ ]:
np.logical_or(c<10,d<20)

array([ True, False, False, False])

## Numpy with datasets

# RegEx

In [2]:
import re

In [3]:
text = "This is a good day."

if re.search("good", text): 
    print("Wonderful!")
else:
    print("Alas :(")

Wonderful!


In [6]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."
re.split("Amy", text)


['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is succesful.']

In [8]:
re.findall("Amy", text)

['Amy', 'Amy', 'Amy']

In [14]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

res = re.search("^Amy",text)
res

<re.Match object; span=(0, 3), match='Amy'>

In [15]:
res.start()

0

In [16]:
res.end()

3

## findall

In [17]:
grades="ACAAAABCBCBAA"

re.findall("B",grades)

['B', 'B', 'B']

In [21]:
re.findall("[AB]",grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [22]:
re.findall("[A][B-C]",grades)

['AC', 'AB']

In [23]:
re.findall("AB|AC",grades)

['AC', 'AB']

In [24]:
re.findall("[^A]",grades) #^ to negate

['C', 'B', 'C', 'B', 'C', 'B']

In [25]:
re.findall("^[^A]",grades) #^ outside means begins with

[]

### more patterns using a txt file and 

# Pandas

## Series

!pip install pandas

In [5]:
import pandas as pd
import numpy as np

In [6]:
students = ['Alice', 'Jack', 'Molly']

pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 90, 88, 92]
}
df = pd.DataFrame(data)
print("\nDataFrame:")
print(df)



DataFrame:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
3    David   40     92


In [ ]:
df.iloc[2]

Name     Charlie
Age           35
Score         88
Name: 2, dtype: object

In [ ]:
df.loc[2]

Name     Charlie
Age           35
Score         88
Name: 2, dtype: object

In [ ]:
df2 = pd.DataFrame(
{
      "A": 1.0,
    "B": pd.Timestamp("20130102"),
       "C": pd.Series(1, index=list(range(4)), dtype="float32"),
            "D": np.array([3] * 4, dtype="int32"),
            "E": pd.Categorical(["test", "train", "test", "train"]),
            "F": "foo",
        }
    )

In [ ]:
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [ ]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [ ]:
# Empty Numpy array
import numpy as np
empty_array = np.empty(shape=(3, 2), dtype=int)
print(empty_array)

[[97167491827468              0]
 [  416611827815   137438953580]
 [  433791697011   459561500773]]


In [ ]:
# Numpy array made of ones
import numpy as np
ones_array = np.ones(shape=(3, 2), dtype=int)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# 2d numpy array with random numbers of dimentions 5,4
import numpy as np
random_array = np.random.rand(5, 4)
print(random_array)


[[0.71858827 0.30403466 0.63112567 0.74419912]
 [0.63006517 0.21640181 0.18516542 0.28770215]
 [0.27599582 0.68473862 0.61724875 0.70440678]
 [0.6279539  0.12024354 0.70145193 0.57942079]
 [0.73684968 0.00717923 0.481965   0.37206044]]


In [ ]:
az3d = np.zeros([2,3,4])
print(az3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
df.head()
df.tail()

NameError: name 'df' is not defined

In [1]:
import pandas as pd
# pd.series({'a':1,'b':2,'c':3})

In [ ]:
pd.read_sql_query("S")